### ISSUE TITLE
Host the library on another repository besides JCenter

### ISSUE THREAD

**Issue by greg-milette-bose** [Chesire/LifecykleLog#198]
Problem: the library is only hosted on jcenter, and jcenter is going away

solution: Please host the library on another place.

**Comment by Chesire** [comment]
Thanks for the suggestion, I'll have a look at hosting it in another location in the future.
In the meantime it should be available via Jitpack until it can be moved elsewhere

**Comment by Chesire** [comment]
Forgot to close, have updated the readme with information on how to pull it from Jitpack.
